version: '3'
services:
  nginx:
    image: nginx:1.13.9-alpine
    ports:
      - "8085:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/app

  app:
    build: ./app_docker
    env_file: ./mysql/.env_db
    depends_on:
      - mysql
    volumes:
      - ./app:/var/www/app

  mysql:
    image: mysql:5.7.21
    env_file: ./mysql/.env_db
    ports:
      - "3309:3306"
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql